name: dev pipeline

on:
  push:
    branches:
      - dev

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        winget install -e --id Astronomer.Astro
        astrocloud deploy --pytest ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}