name: dev pipeline

on:
  push:
    branches:
      - dev

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Verify Astronomer CLI Installation
      run: |
        echo "Checking if Astronomer CLI is installed..."
        where astro.exe || echo "astro.exe not found"

    - name: Deploy to Astro
      run: |
        astro cloud deploy --pytest ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}
