name: dev pipeline

on:
  push:
    branches:
      - dev

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4
      
    - name: Install Astronomer CLI
      run: |
        curl -sSL https://install.astronomer.io | bash
        echo 'export PATH="$HOME/.astro/bin:$PATH"' >> $GITHUB_ENV
      
    - name: Deploy to Astro
      run: |
        astrocloud deploy --pytest ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}