name: dev pipeline

on:
  push:
    branches:
      - dev

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Install Astronomer CLI
      run: |
        wget -qO- https://get.astronomer.io | bash
        echo "$HOME/.astro/bin" >> $GITHUB_PATH
        # Check if the installation succeeded
        ls -la $HOME/.astro/bin

    - name: Verify Astronomer CLI Installation
      run: |
        echo 'PATH=$HOME/.astro/bin:$PATH' >> $GITHUB_ENV
        source $GITHUB_ENV
        which astro || echo "astro not found"
        astro --version || echo "Failed to get astro version"

    - name: Deploy to Astro
      run: |
        source $GITHUB_ENV
        astrocloud deploy --pytest ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}
      env:
        ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
